blog/urls.py
from django.urls import path
from . import views
from django.views.generic.base import TemplateView

app_name = 'blog'
urlpatterns = [
    path('<int:page>/', views.index, name='index'),
    path('<int:year>/<int:month>/', views.archives, name='archives'),
    path('category/<int:category>/', views.categories, name='categories'),
    path('post/<int:post_id>/', views.detail, name='detail'),
    path('about/', TemplateView.as_view(template_name="blog/about.html"), name='about'),
    path('contact/', TemplateView.as_view(template_name="blog/contact.html"), name='contact'),
    path('full-width/', TemplateView.as_view(template_name="blog/full-width.html"), name='full-width'),
]

mysite/urls.py
from django.contrib import admin
from django.views import debug
from django.urls import path, include

urlpatterns = [
    path('', debug.default_urlconf, name='index'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=20)

    def get_absolute_url(self):
        return "blog/category/%i/" % self.id

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20)

    def get_absolute_url(self):
        return "blog/tag/%i/" % self.id

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag)

    def get_absolute_url(self):
        return "/blog/post/%i/" % self.id

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
import markdown


# Create your views here.
def index(request, page):
    post_list = Post.objects.order_by('-created_time')[(page - 1) * 5:page * 5]
    return render(request, 'blog/index.html', {
        'post_list': post_list,
    })


def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.body = markdown.markdown(post.body, extensions=['markdown.extensions.toc', 'markdown.extensions.sane_lists',
                                                         'markdown.extensions.codehilite',
                                                         'markdown.extensions.fenced_code'])
    comment_list = Comment.objects.filter(post=post_id).order_by('-created_time')
    return render(request, 'blog/detail.html', {'post': post, 'comment_list': comment_list})


def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month)
    return render(request, 'blog/index.html', {'post_list': post_list})


def categories(request, category):
    post_list = Post.objects.filter(id=category)
    return render(request, 'blog/index.html', {'post_list': post_list})
#
#
# def about(request):
#     return render(request, 'blog/about.html')
#
#
# def contact(request):
#     return render(request, 'blog/contact.html')

blog/templates/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'blog/css/icons.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}"/>
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}"/>

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' 1 %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="/" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="博客">博客</a>
                            </li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="联系">联系</a>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block detail %}
                <article class="post post-{{ post.id }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{ post.modified_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.body|safe }}</p>
                    </div>
                </article>
                {% endblock %}
                {% block articles %}
                {% for post in post_list %}
                    <article class="post post-{{ post.id }}">
                        <header class="entry-header">
                            <h1 class="entry-title">
                                <a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a>
                            </h1>
                            <div class="entry-meta">
                                <span class="post-category"><a href="#">{{ post.category }}</a></span>
                                <span class="post-date"><a href="#"><time class="entry-date"
                                                                          datetime="2012-11-09T23:15:57+00:00">{{ post.modified_time }}</time></a></span>
                                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                                <span class="comments-link"><a href="#">4 评论</a></span>
                                <span class="views-count"><a href="#">588 阅读</a></span>
                            </div>
                        </header>
                        <div class="entry-content clearfix">
                            {% if post.excerpt %}
                                <p>{{ post.excerpt }}</p>
                            {% else %}
                                <p>{{ post.body|slice:'66' }}</p>
                            {% endif %}
                            <div class="read-more cl-effect-14">
                                <a href="{% url 'blog:detail' post.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                            </div>
                        </div>
                    </article>
                {% endfor %}
                {% endblock %}
                {% block section %}
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:comment' post.id %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label>
                                <textarea name="text" id="id_comment" required></textarea>
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <hr>
                    <div class="comment-list-panel">
                        <h3>评论列表,共{{ comment_list|length }}条评论</h3>
                        <ul class="comment-list list-unstyled">
                        {% for comment in comment_list %}
                            <li class="comment-item">
                            <span class="nickname">{{ comment.name }}</span>
                            <time class="submit-date">{{ comment.created_time }}</time>
                            <div class="text">
                                {{ comment.text }}
                            </div>
                        </li>
                        {% empty %}
                        暂无评论
                        {% endfor %}
                        </ul>
                    </div>
                </section>
                {% endblock %}
                {% block pagination %}
            <div class="pagination">
                {% get_count as num %}
                <ul>
                {% for p in num %}
                    <li><a href="{% url 'blog:index' p %}">{{ p }}</a></li>
                {% endfor %}
                </ul>
            </div>
            {% endblock %}
            </main>
            {% block toc %}
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    <ul>
                        <li>
                            <a href="#">教程特点</a>
                        </li>
                        <li>
                            <a href="#">谁适合这个教程</a>
                        </li>
                        <li>
                            <a href="#">在线预览</a>
                        </li>
                        <li>
                            <a href="#">资源列表</a>
                        </li>
                        <li>
                            <a href="#">获取帮助</a>
                        </li>
                    </ul>
                </div>
            {% endblock %}
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_posts_list %}
                    <ul>
                        {% for post in recent_posts_list %}
                            <li>
                                <a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
                                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:categories' category.name %}">{{ category.name }} <span class="post-count">({{ category.post__count }})</span> </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                            <li>
                                <a href="#">{{ tag.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="/">首页</a></li>
            <li><a href="{% static 'blog/blog/full-width.html' %}">博客</a></li>
            <li><a href="{% static 'blog/blog/about.html' %}">关于</a></li>
            <li><a href="{% static 'blog/blog/contact.html' %}">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

blog/templates/blog/about.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Black &amp; White</title>

        <!-- meta -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- css -->
        <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/icons.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}"/>

        <!-- js -->
        <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

    </head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{% url 'blog:index' 1 %}"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{% url 'blog:index' 1 %}" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:full-width' %}" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="#" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="../../static/blog/img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="{% static 'blog/js/script.js' %}"></script>
		
	</body>
</html>

blog/templates/blog/contact.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Black &amp; White</title>

        <!-- meta -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- css -->
        <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/icons.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}"/>

        <!-- js -->
        <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

    </head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{% url 'blog:index' 1 %}"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{% url 'blog:index' 1 %}" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:full-width' %}" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="{% static 'blog/js/script.js' %}"></script>
		
	</body>
</html>

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% block articles %}{% endblock %}
{% block pagination %}{% endblock %}

blog/templates/blog/full-width.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
        <title>Black &amp; White</title>

        <!-- meta -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- css -->
        <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/icons.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}"/>

        <!-- js -->
        <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

    </head>

	<body>
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{% url 'blog:index' 1 %}"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{% url 'blog:index' 1 %}" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="#" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<article class="post post-1">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="detail.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#">Web Design</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>
			
									<span class="post-author"><a href="#">Albert Einstein</a></span>
			
									<span class="comments-link"><a href="">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>

						<article class="post post-2">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="detail.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#">Web Design</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>
			
									<span class="post-author"><a href="#">Albert Einstein</a></span>
			
									<span class="comments-link"><a href="#">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>

						<article class="post post-3">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="detail.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#" rel="category tag">Web Design</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>
			
									<span class="post-author"><a href="#">Albert Einstein</a></span>
			
									<span class="comments-link"><a href="#">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>

						<article class="post post-4">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="detail.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#" rel="category tag">Web Design</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>
			
									<span class="post-author"><a href="#">Albert Einstein</a></span>
			
									<span class="comments-link"><a href="#">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="../../static/blog/js/script.js"></script>

	</body>
</html>

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block detail %}{% endblock %}
{% block section %}{% endblock %}
{% block toc %}{% endblock %}